version: '3.4'

services:
  marketplaceforyou.api:
    image: ${DOCKER_REGISTRY-}marketplaceforyouapi
    container_name: "marketplaceforyou.api"
    build:
      context: .
      dockerfile: MarketPlaceForYou.Api/Dockerfile
    ports: 
      - '35010:80'
      - '35020:443'
    environment:
      - Auth0__Domain=https://marketforyou.us.auth0.com
      - Auth0__Audience=http://marketforyou.com
      - Auth0__TokenRedirectUrl=http://localhost:35010
      - AWS__ImageBucket=marketforyou-yh
      - AWS__Region=ca-central-1
    volumes:
      - .aws/root/.aws
    depends_on:
        - marketplaceforyou.db

  marketplaceforyou.db:
    restart: on-failure
    image: "postgis/postgis:14-3.2-alpine"
    container_name: "marketplaceforyou.db"
    environment:
    - POSTGRES_USER=dbuseryasin
    - POSTGRES_PASSWORD=launchpadmay2022project
    - POSTGRES_DB=mkpfydb
    volumes:
    - marketplaceforyou-db:/var/lib/postgresql/data
    ports:
    - "35025:5432"
volumes:
    marketplaceforyou-db:

